### ISSUE TITLE
Startup Error: ClassNotFoundException

### ISSUE THREAD

**Issue by schaarda** [otros-systems/OtrosJumpToCode#11]
Hello,
I'm using the JumpToCodePlugin 1.9 with intelliJ 2022.2.4 (same with 2022.2.3). Whenever the plugin activated and I start IntelliJ I get the following error message:

> Plugin 'pl.otros.intellij.JumpToCode' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
java.lang.ClassNotFoundException: pl.otros.intellij.jumptocode.logic.OtrosJumpToCodeApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=OtrosJumpToCode, id=pl.otros.intellij.JumpToCode, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2022.2\plugins\OtrosJumpToCode, version=1.9, package=null, isBundled=false), packagePrefix=null, instanceId=43, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:449)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:370)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:55)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:251)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:148)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by bodzebod** [comment]
Similar error for me:

Caused by: java.lang.ClassNotFoundException: pl.otros.intellij.jumptocode.logic.OtrosJumpToCodeApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=OtrosJumpToCode, id=pl.otros.intellij.JumpToCode, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.1\plugins\OtrosJumpToCode, version=1.9, package=null, isBundled=false), packagePrefix=null, instanceId=69, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:536)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:408)
    ... 26 more

-----
Your JRE: 17.0.6+10-b829.9 amd64 (JetBrains s.r.o.)
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\jbr

**Comment by mangrajalkin** [comment]
Same for me, on 2023.1.3:

```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: Fatal error initializing 'pl.otros.intellij.jumptocode.logic.OtrosJumpToCodeApplicationComponent
            ' [Plugin: pl.otros.intellij.JumpToCode]
    at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:612)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:416)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:69)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:294)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
    at com.intellij.idea.ApplicationLoader.doInitApplication(ApplicationLoader.kt:86)
    at com.intellij.idea.ApplicationLoader.access$doInitApplication(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$doInitApplication$1.invokeSuspend(ApplicationLoader.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:63)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at com.intellij.idea.J.f(J.java:73)
    at com.intellij.ide.J.o.fV.f(fV.java:139)
    at com.intellij.ide.J.o.Jb.J(Jb.java:196)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at com.intellij.idea.MainImpl.start(MainImpl.kt:62)
    at com.intellij.idea.StartupUtil$startApplication$7.invokeSuspend(StartupUtil.kt:297)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.Main.main(Main.kt:40)
Caused by: java.lang.ClassNotFoundException: pl.otros.intellij.jumptocode.logic.OtrosJumpToCodeApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=OtrosJumpToCode, id=pl.otros.intellij.JumpToCode, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38.plugins/OtrosJumpToCode, version=1.9, package=null, isBundled=false), packagePrefix=null, instanceId=104, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:536)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:408)
    ... 33 more

-----
Your JRE: 17.0.7+10-b829.16 amd64 (JetBrains s.r.o.)
/home/mangrajalkin/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/jbr
```
